services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-api
  web-api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: web-api
    env_file:
      - .env
    depends_on:
      - pg-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    command: [ "fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000" ]

  pg-container:
    image: postgres:15
    container_name: pg_container
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  pg_data:
